// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package tema2_ISP;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;

/************************************************************/
/**
 * 
 */
public class Administrator extends tema2_ISP.User {
	public static final int MAX_AGENTI = 100;
	Administrator(String email_user, String parola, String tip_utilizator) {
		super(email_user, parola, tip_utilizator);
		// TODO Auto-generated constructor stub
		this.loadPossibilities(tip_utilizator);
	}
	void loadPossibilities(String tip_user) {
		System.out.println("Contul dvs de "+tip_user+" a fost creat cu succes");
		System.out.println("Aveti posibilitatea urmatoarelor operatii:");
		System.out.println("1.Schimbare username");
		System.out.println("2.Schimbare parola");
		System.out.println("3.Logout");
		System.out.println("4.Adauagare Agent Turism");
		System.out.println("5.Stergere Agent Turism");
		System.out.println("6.Generare View de Profit");
		BufferedReader input_client = new BufferedReader(new InputStreamReader (System.in));
		String optiune_client;
		try {
			optiune_client = new String(input_client.readLine());
				switch(optiune_client) {
				case "1":{
					BufferedReader input_new_username= new BufferedReader(new InputStreamReader (System.in));
					System.out.println("Introduceti noul username: ");
					try {
						String new_username = new String(input_new_username.readLine());
						super.change_username(new_username);
					}
					catch(IOException e1) {
						e1.printStackTrace();
					}	
					break;
					
				}
				case "2":{
					System.out.println("Introduceti noua parola:");
					BufferedReader input_new_parola= new BufferedReader(new InputStreamReader (System.in));
					try {
						String new_pass = new String(input_new_parola.readLine());
						super.setPass(new_pass);
					}
					catch(IOException e1) {
						e1.printStackTrace();
					}	
					break;
				}
				case "3":{
					super.logout();
					break;
				}
				case "4":{
					//TO_DO #5
					String email_agent_nou = "";
					String noua_parola = "";
					this.adaugareAgent(email_agent_nou, noua_parola);
					break;
				}
				case "5":{
					//TO_DO #6
					String email_agent_vechi = "";
					this.stergereAgent(email_agent_vechi);
					break;
				}
				case "6":{
					//TO_DO_LA_FINAL DACA AVEM TIMP,LEL
					this.generateProfitView();
					break;
				}
			}
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	/**
	 * 
	 */
	public tema2_ISP.AgentTurism[] agentturism = new tema2_ISP.AgentTurism[MAX_AGENTI];

	/**
	 * 
	 * @param Email 
	 * @param Parola 
	 */
	public void adaugareAgent(String Email, String Parola) {
		
		//TO_DO #5
	}

	/**
	 * 
	 * @param Email 
	 */
	public void stergereAgent(String Email) {
		
		//TO_DO #6
	}

	/**
	 * 
	 */
	public void generateProfitView() {
		
		//TO_DO de final
	}
};
