// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package tema2_ISP;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;

/************************************************************/
/**
 * 
 */
public class AgentTurism extends tema2_ISP.User {
	AgentTurism(String email_user, String parola, String tip_utilizator) {
		super(email_user, parola, tip_utilizator);
		this.loadPossibilities(tip_utilizator);
		// TODO Auto-generated constructor stub
	}
	
	void loadPossibilities(String tip_user) {
		System.out.println("Contul dvs de "+tip_user+" a fost creat cu succes");
		System.out.println("Aveti posibilitatea urmatoarelor operatii:");
		System.out.println("1.Schimbare username");
		System.out.println("2.Schimbare parola");
		System.out.println("3.Logout");
		System.out.println("4.Validare comanda client");
		System.out.println("5.Invalidare comanda client");
		BufferedReader input_client = new BufferedReader(new InputStreamReader (System.in));
		String optiune_client;
		this.validat = false;
		try {
			optiune_client = new String(input_client.readLine());
				switch(optiune_client) {
				case "1":{
					BufferedReader input_new_username= new BufferedReader(new InputStreamReader (System.in));
					System.out.println("Introduceti noul username: ");
					try {
						String new_username = new String(input_new_username.readLine());
						super.change_username(new_username);
					}
					catch(IOException e1) {
						e1.printStackTrace();
					}	
					break;
					
				}
				case "2":{
					System.out.println("Introduceti noua parola:");
					BufferedReader input_new_parola= new BufferedReader(new InputStreamReader (System.in));
					try {
						String new_pass = new String(input_new_parola.readLine());
						super.setPass(new_pass);
					}
					catch(IOException e1) {
						e1.printStackTrace();
					}	
					break;
				}
				case "3":{
					super.logout();
				}
				case "4":{
					//TO_DO #3
					
					//A SE IMPLEMENTA DUPA TO_DO #2
					String client_email = "";
					String cod_comanda = "";
					this.validat = this.validareRezervare(client_email, cod_comanda);
					break;
				}
				case "5":{
					//TO_DO #4
					//A SE IMPLEMENTA DUPA TO_DO #3
					String client_email = "";
					String cod_comanda = "";
					this.validat = this.invalidareRezervare(client_email, cod_comanda);
					break;
					
				}
			}
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	/**
	 * 
	 */
	private boolean validat;
	/**
	 * 
	 */
	public tema2_ISP.Rezervari[] rezervari;

	/**
	 * 
	 * @param client_email 
	 * @param cod_comanda 
	 * @return 
	 */
	public boolean validareRezervare(String client_email, String cod_comanda) {
		//TO_DO #3
		return true;
	}

	/**
	 * 
	 * @param client_name 
	 * @param cod_comanda 
	 * @return 
	 */
	public boolean invalidareRezervare(String client_name, String cod_comanda) {
		//TO_DO #4
		return false;
	}

	/**
	 * 
	 * @param criteriu_filtrare_comenzi 
	 */
	public void filtrare(tema2_ISP.Filtre_agent criteriu_filtrare_comenzi) {
		
		//TO_DO #5
	}

	public boolean isValidat() {
		return validat;
	}

	public void setValidat(boolean validat) {
		this.validat = validat;
	}
};
