// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package tema2_ISP;

/************************************************************/
/**
 * 
 */
public enum Categorie_Oferta {
	/**
	 * 
	 */
	InchiriereMasina,
	/**
	 * 
	 */
	SejurHotel,
	/**
	 * 
	 */
	RezervareBiletAvion;
};
