// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package tema2_ISP;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;

/************************************************************/
/**
 * 
 */
public class Client extends tema2_ISP.User {
	Client(String email_user, String parola, String tip_utilizator) {
		super(email_user, parola, tip_utilizator);
		this.loadPossibilities(tip_utilizator);
		// TODO Auto-generated constructor stub
	}
	
	void loadPossibilities(String tip_user) {
		System.out.println("Contul dvs de "+tip_user+" a fost creat cu succes");
		System.out.println("Aveti posibilitatea urmatoarelor operatii:");
		System.out.println("1.Schimbare username");
		System.out.println("2.Schimbare parola");
		System.out.println("3.Logout");
		System.out.println("4.Generare comanda");
		System.out.println("5.Vizualizari istoric comenzi");
		BufferedReader input_client = new BufferedReader(new InputStreamReader (System.in));
		String optiune_client;
		try {
			optiune_client = new String(input_client.readLine());
				switch(optiune_client) {
				case "1":{
					BufferedReader input_new_username= new BufferedReader(new InputStreamReader (System.in));
					System.out.println("Introduceti noul username: ");
					try {
						String new_username = new String(input_new_username.readLine());
						super.change_username(new_username);
					}
					catch(IOException e1) {
						e1.printStackTrace();
					}	
					break;
					
				}
				case "2":{
					System.out.println("Introduceti noua parola:");
					BufferedReader input_new_parola= new BufferedReader(new InputStreamReader (System.in));
					try {
						String new_pass = new String(input_new_parola.readLine());
						super.setPass(new_pass);
					}
					catch(IOException e1) {
						e1.printStackTrace();
					}	
					break;
				}
				case "3":{
					super.logout();
					break;
				}
				case "4":{
					//SPECIFICA CLIENTULUI 
					
					//#TO_DO_1
					//A SE IMPLEMENTA MAI INTAI CLASELE DE ASOCIATIE 
					//RESPECTIV CEALALTA GENERALIZARE DE PE OFERTE
					String cod_comanda = "";
					this.generare_comanda(cod_comanda);
					break;
					
				}
				case "5":{
					//SPECIFICA CLIENTULUI 
					this.vizualizareIstoricRezervari();
					break;
					//#TO_DO_2
					//A SE IMPLEMENTA MAI INTAI CLASA REZERVARI CU COMPOZITIILE CATRE REZERVARIBILETAVION, etc(cele 3 clase de asociatie)s
				}
			}
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	/**
	 * 
	 */
	private tema2_ISP.Categorie_Oferta current_selection;
	/**
	 * 
	 */
	private float pret_comanda_curenta;

	/**
	 * 
	 * @param cod_comanda 
	 */
	public void generare_comanda(String cod_comanda) {
		//TO_DO #1
	}

	/**
	 * 
	 */
	public void vizualizareIstoricRezervari() {
		//TO_DO #2
	}

	/**
	 * 
	 * @param cod_comanda_viz 
	 */
	public void vizualizareDetaliiComanda(String cod_comanda_viz) {
		//TO_DO #1
	}

	/**
	 * 
	 * @param suma 
	 * @param cod_comanda 
	 */
	public void plata_comanda(float suma, String cod_comanda) {
		//TO_DO #1
	}

	public float getPret_comanda_curenta() {
		return pret_comanda_curenta;
	}

	public void setPret_comanda_curenta(float pret_comanda_curenta) {
		this.pret_comanda_curenta = pret_comanda_curenta;
	}

	public tema2_ISP.Categorie_Oferta getCurrent_selection() {
		return current_selection;
	}

	public void setCurrent_selection(tema2_ISP.Categorie_Oferta current_selection) {
		this.current_selection = current_selection;
	}
};
