// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package tema2_ISP;

/************************************************************/
/**
 * 
 */
public class OferteMasini extends tema2_ISP.Oferte {
	OferteMasini(tema2_ISP.Categorie_Oferta categorie, String detalii_oferta) {
		super(categorie, detalii_oferta);
		// TODO Auto-generated constructor stub
	}

	public String getUnitate_pret() {
		return unitate_pret;
	}

	public void setUnitate_pret(String unitate_pret) {
		this.unitate_pret = unitate_pret;
	}

	public int getNrOreInchiriere() {
		return nrZileInchiriere;
	}

	public void setNrOreInchiriere(int nrZileInchiriere) {
		this.nrZileInchiriere = nrZileInchiriere;
	}

	public float getPret_total() {
		return pret_total;
	}

	public void setPret_total() {
		this.pret_total = super.Pret*this.getNrOreInchiriere();
	}

	public String getMarca() {
		return marca;
	}

	public void setMarca(String marca) {
		this.marca = marca;
	}

	public int getNrLocuri() {
		return nrLocuri;
	}

	public void setNrLocuri(int nrLocuri) {
		this.nrLocuri = nrLocuri;
	}

	/**
	 * 
	 */
	private String unitate_pret = "Ora";
	private int nrZileInchiriere;
	private String marca;
	private int nrLocuri;
	private float pret_total;
	
	
};
