// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package tema2_ISP;

/************************************************************/
/**
 * 
 */
public class Rezervari {
				/**
				 * 
				 */
				private String nrRezervare;
				/**
				 * 
				 */
				private String cod_comanda;
				/**
				 * 
				 */
				/*contine RezervariBiletAvion , RezervariHotel, RezervariMasini (compozitii)
				/**
				 * 
				 */
				private boolean validata;
				public String getNrRezervare() {
					return nrRezervare;
				}
				public void setNrRezervare(String nrRezervare) {
					this.nrRezervare = nrRezervare;
				}
				public String getCod_comanda() {
					return cod_comanda;
				}
				public void setCod_comanda(String cod_comanda) {
					this.cod_comanda = cod_comanda;
				}
				public boolean isValidata() {
					return validata;
				}
				public void setValidata(boolean validata) {
					this.validata = validata;
				}
};
