// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package tema2_ISP;

/************************************************************/
/**
 * 
 */
public class User {
	/**
	 * 
	 */
	protected String Email;
	/**
	 * 
	 */
	private String password;
	/**
	 * 
	 */
	public String username;
	/**
	 * 
	 */
	private String tip_user;
	/**
	 * 
	 */
	protected boolean logat;
	/**
	 * 
	 */
	protected boolean hasAccount;
	
	private String cod_user;
	
	public int countIDs = 0;
	
	
	
	public void afisareUser() {
		System.out.println("Email user: "+this.Email);
		System.out.println("Username: "+this.username);
		
	}
	
	User(String email_user,String parola,String tip_utilizator){
		countIDs++;
		//constructor pentru user cu email_user,parola,tip_utilizator
		this.setTip_user(tip_utilizator);
		this.setPass(parola);
		this.Email = email_user;
		this.change_username("None");
		//generam cod individual de identificare pentru user
		String cod_generat = tip_utilizator + String.valueOf(countIDs);
		this.setCod_user(cod_generat);
	}
	/**
	 * 
	 */
	public void logout() {
		this.logat = false;
		System.exit(1);
	}

	/**
	 * 
	 * @param user_email 
	 * @param user_pass 
	 * @return 
	 */
	public boolean login(String user_email, String user_pass) {
		return false;
	}


	/**
	 * 
	 * @param password 
	 */
	public void setPass(String pass) {
		this.password = pass;
		
	}

	/**
	 * 
	 */
	public String getPass() {
		return this.password;
	}

	/**
	 * 
	 * @param password 
	 */
	//VA PICA PANA SE VA IMPLEMENTA CU BD
	public void resetPassWithEmail(String password) {
	}

	/**
	 * 
	 */
	public void create_account() {
		
	}

	/**
	 * 
	 * @param new_username 
	 */
	public void change_username(String new_username) {
		this.username = new_username;
	}

	/**
	 * 
	 * @param email_search 
	 * @return 
	 */
	
	//PICA PANA LA O IMPLEMENTARE CU BD
	public boolean get_Account(String email_search) {
		return false;
	}

	/**
	 * 
	 * @param email 
	 * @param password 
	 * @param username 
	 */
	public void saveChanges(String email, String password, String username) {
		this.Email = email;
		this.setPass(password);
		this.change_username(username);
	}
	public String getTip_user() {
		return tip_user;
	}
	public void setTip_user(String tip_user) {
		this.tip_user = tip_user;
	}
	public String getCod_user() {
		return cod_user;
	}
	public void setCod_user(String cod_user) {
		this.cod_user = cod_user;
	}
};
